'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BeecomePOS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Public ReadOnly Property _1412607468_resultset_first() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1412607468_resultset_first", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property _1412607468_resultset_first1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1412607468_resultset_first1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property _256px_Icon_information_svg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("256px-Icon-information.svg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property _5bath() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5bath", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property address_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("address_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property application() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("application", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property arrow_090() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow-090", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property arrow_0901() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow-0901", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property arrow_180() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow-180", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property arrow_270() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow-270", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property arrow_circle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow-circle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property arrow_circle_double_135() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow-circle-double-135", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property arrow_curve() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow-curve", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property arrow_curve_180() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow-curve-180", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property arrow_curve_1801() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow-curve-1801", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property arrow_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property arrow_right1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_right1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property arrow_right2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_right2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property arrow1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property baht_salary_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baht_salary-512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bg_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bg_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bg_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bg_33() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_33", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bg_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bg_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bg_51() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_51", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bg_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bg_blue_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_blue_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bg_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bg_left1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_left1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bg_menu_bar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_menu_bar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bg_menu_bar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_menu_bar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bg_menu_bar11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_menu_bar11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bg_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bg_panal3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_panal3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bg_panal31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_panal31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bg_pic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_pic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bg_pink() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_pink", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bgCenter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bgCenter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bgTabMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bgTabMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property blue_coffee_2_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue_coffee_2_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property blue_with_silver_frame() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue-with-silver-frame", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bread1_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bread1_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property bread1_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bread1_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property breads_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("breads_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btn_addorder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_addorder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btn_backH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_backH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btn_backP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_backP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btn_drow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_drow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btn_hold() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_hold", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btn_logout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_logout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btn_minus1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_minus1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btn_ok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_ok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btn_opn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_opn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btn_pay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_pay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btn_plus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_plus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btn_plus1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_plus1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btn_reload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_reload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btn_res() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_res", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btn_reserv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_reserv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btn_reset() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_reset", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btn_sel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_sel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btn_sel1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_sel1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btn_sendorder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_sendorder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btn_trybill() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_trybill", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btn_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btn_view() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_view", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property btn_walking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_walking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property buy_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buy_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property cake_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cake_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property calendar_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calendar_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Cart_Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cart-Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Cart_Add1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cart-Add1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property clipboard_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clipboard_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property clipboard_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clipboard_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property clipboard_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clipboard_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property coffee_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coffee_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Compile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Compile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Compile1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Compile1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Computer_Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Computer-Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property cookies_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cookies_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property cross() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cross", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property currency_collection_019() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("currency-collection-019", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Datbase_Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Datbase-Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Datbase_Lock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Datbase-Lock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property del16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("del16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property delete_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property delete_161() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_161", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property delete_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property delete_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property diagram_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diagram_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property discounts_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("discounts-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property disk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Doc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Doc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Doc_Del() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Doc-Del", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Doc_Edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Doc-Edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property document_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property edit_user1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_user1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property English_Flag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("English-Flag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property English_Flag__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("English-Flag (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Favorite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Favorite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property file_complete_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("file-complete-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property flag_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property flag_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Flag_Blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Flag-Blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Flag_Cyan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Flag-Cyan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property flag_uk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag-uk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property flag_uk1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flag-uk1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property food_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("food_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property food1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("food1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property food11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("food11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property food12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("food12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property food13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("food13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Forbidden() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Forbidden", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Forbidden1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Forbidden1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property FreeVector_Blue_Squares_Vector() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FreeVector-Blue-Squares-Vector", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property french_fries_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("french_fries_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property gear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property gear_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gear_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property gear_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gear_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property hm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property hm1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hm1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property hm2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hm2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Home() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Home", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property home_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property hot_dog_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hot_dog_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property icon_payment2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon-payment2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property inven() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inven", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property inven45() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inven45", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property invoice_send() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invoice_send", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property invoice_send1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invoice_send1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property iphoto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iphoto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Key() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Key", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property key_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property label_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("label_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property left_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("left_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property left_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("left_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property left_all() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("left_all", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property leftred_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("leftred_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property leftred_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("leftred_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property login_bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login_bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property login_bg1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login_bg1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property login_bg11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login_bg11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property login_new_button_zpse5e3fd1f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login_new_button_zpse5e3fd1f", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property login_new_button_zpse5e3fd1f1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login_new_button_zpse5e3fd1f1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property logo_bg1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_bg1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property logo_bg11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_bg11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property logo_menu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_menu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property logo_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property m_close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m_close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property m_closerop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m_closerop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property m_logout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m_logout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property m_maxsize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m_maxsize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property m_mini() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m_mini", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property m_opentb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m_opentb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property m_opentb1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m_opentb1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property m_opentb2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m_opentb2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property m_report() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m_report", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property m_reserv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m_reserv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property m_walking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m_walking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property menu_bar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_bar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property menu_bar_bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_bar_bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property menu_bar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_bar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property menu_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property milkshake_chocolate_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("milkshake_chocolate_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property minus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property minus1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minus1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property monitor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("monitor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property News_Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("News-Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property News_Del() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("News-Del", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property News_Edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("News-Edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Ok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property p1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property p2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property pencil_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pencil_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property pencil_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pencil_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property pencil_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pencil_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property pizza_slice_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pizza_slice_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property plus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property plus_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plus_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property plus_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plus_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property plus_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plus_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property plus1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plus1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property plus2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plus2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property pos_icon5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pos-icon5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property pre_print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pre_print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property print_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property print32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property printer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property prohibition() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prohibition", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property question_mark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("question-mark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property reserv1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reserv1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property right_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("right_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property right_all() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("right_all", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property save_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property save_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property search_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property search_161() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_161", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property search_162() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_162", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property sliced_bread_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sliced_bread_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property soft_drink_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("soft_drink_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property stop_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stop_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property sup_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sup_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Tag_Blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tag-Blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Tag_Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tag-Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property tankehome1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tankehome1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property tb1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tb1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property tb2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tb2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property tb21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tb21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property tb22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tb22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property tb23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tb23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property th() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("th", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property tick_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tick_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property title_bar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("title_bar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property title_bar_bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("title_bar_bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property total_user1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("total-user1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property total_user11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("total-user11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Trash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property trash_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trash_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property trash_161() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trash_161", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property trash_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trash_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Trend_Down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trend Down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Trend_Up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trend Up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property User() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property User__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User (2)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property user_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property User_Del() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User-Del", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property User_Edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User-Edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property viewbill1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("viewbill1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Web_info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Web-info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property wine_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wine_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Wizard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wizard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
